
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 30 15:57:50 CST 2014
//----------------------------------------------------

package tvla.jeannet.language.TVP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UPDATE_COLON = 49;
  public static final int FORALL = 9;
  public static final int LCBR = 27;
  public static final int FUNCTION = 41;
  public static final int DIFF_OVER = 58;
  public static final int RETAIN_COLON = 48;
  public static final int RBR = 37;
  public static final int PRED = 5;
  public static final int PREFAB = 60;
  public static final int COERCE = 61;
  public static final int MINUS = 35;
  public static final int EMBEDBLUR = 52;
  public static final int STAR = 16;
  public static final int NOT = 15;
  public static final int SEMICOLON = 31;
  public static final int AND = 14;
  public static final int COPY = 66;
  public static final int COMBINE = 39;
  public static final int IN = 63;
  public static final int LP = 23;
  public static final int OR = 13;
  public static final int QMARK = 29;
  public static final int COMMA = 26;
  public static final int IMPLIES = 12;
  public static final int BEGIN = 64;
  public static final int JOINWITH = 57;
  public static final int RP = 24;
  public static final int DIFF_UNDER = 59;
  public static final int IMPLIES_T = 4;
  public static final int PLUS = 17;
  public static final int ASSIGN = 25;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int RCBR = 28;
  public static final int HALT_COLON = 44;
  public static final int TRUE = 20;
  public static final int error = 1;
  public static final int PERCENT = 32;
  public static final int NEW_COLON = 46;
  public static final int EXISTS = 8;
  public static final int JOIN = 53;
  public static final int JOINFOREACH = 56;
  public static final int AUTO = 40;
  public static final int NEQ = 19;
  public static final int MEETFOREACH = 55;
  public static final int UNKNOWN = 22;
  public static final int EQ = 18;
  public static final int ARROW = 67;
  public static final int BLUR = 51;
  public static final int CLONE_COLON = 47;
  public static final int FOREACH = 33;
  public static final int CONSISTENCY_RULE = 7;
  public static final int COLON = 30;
  public static final int TITLE = 38;
  public static final int MESSAGE_COLON = 45;
  public static final int LET = 62;
  public static final int LBR = 36;
  public static final int END = 65;
  public static final int INS_PRED = 6;
  public static final int STRING = 2;
  public static final int TC = 10;
  public static final int MEETWITH = 54;
  public static final int FOCUS = 42;
  public static final int TRANSFORM = 50;
  public static final int FALSE = 21;
  public static final int PRECOND_COLON = 43;
  public static final int IFF = 11;
  public static final int SET = 34;
}

